# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Create Release.txt
        run: |
          (
            printf "repository_url\t%s\n" "${{github.repositoryUrl}}"
            printf "ref\t%s\n" "${{github.ref}}"
            printf "ref\t%s\n" "${{github.sha}}"
          ) | tee release.txt

      - name: Create assets
        run: |
          ./copy-settings.sh ./release
          mv release.txt ./release
          cd release
          tar -zcvf ../release.tar.gz .

      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: release.tar.gz
          path: release.tar.gz

      - name: Create Release (on push tags only)
        id: create_release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          tag_name:  ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
            **Full Changelog**: https://github.com/rmatttu/mpv-config/compare/0.0.0...0.0.0
          draft: true
          prerelease: false

      - name: Upload Release Assets  (on push tags only)
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release.tar.gz
          asset_name: release.tar.gz
          asset_content_type: application/gzip
